### 
GET http://localhost:8000/sanctum/csrf-cookie

### 
POST http://localhost:8000/login
X-XSRF-TOKEN: eyJpdiI6InVoTS83Z0N6aWZGTm5DUGRuUWRMZEE9PSIsInZhbHVlIjoiTmUzMzkvYU9acGkveXFQcG5vODVtU2RJZVFEUGJTWmM4bnZPT0E3NnFvTXhqd29vR09yZzhEZUp0eXNlbUxNT091dVdRM1VoWUhYZVFUYkY0Lzc3ajVBSDBDNklKVTlRaXRwREREK0hRSFdka2ZiakwzejB4ZUo4b2F0Y01WcUQiLCJtYWMiOiIyNzkzMjNjYzUwYmQzNGQwMjI4ZTAxZjgzOGY5MDdhZGU5NzEyMzA3MjRlMjBjOWYxMzJlMzQ1MTQ3ZTQ3Y2EyIiwidGFnIjoiIn0%3D

###
POST http://localhost:8000/api/operation
Content-Type: application/json
Authorization: Bearer 17ec761dbede2b094d6e2659ab0dfe7a7e54182486699183fdf88e18b2980dc2

{
    "token": "123456",
    "operation": 1,
    "antenna": 5
}